### ISSUE TITLE
Compiling parameters

### ISSUE THREAD

**Issue by alejandroandreu** [example42/puppet-zabbix_agent#1]
Is is possible to manually specify the flags that will be used to compile Zabbix from source? For instance, I need JMX and IPMI support and these features can only be used when compiling from source.

Thanks for your time,
Alejandro

**Comment by tuxmea** [comment]
@alejandroandreu I would recommend to have a build process in a CI/CD and not use Puppet to compile code from source.
Can we close this issue?
