### ISSUE TITLE
agent test isuue

### ISSUE THREAD

**Issue by kemalsaruhan** [example42/puppet-zabbix_agent#10]
## Expected Behavior 
Hi, 
The usege of the module is not described detailly. I'm new to the puppet. I have edited init.pp. I get the following error.

## Actual Behavior
Error: RPMs must specify a package source
Error: /Stage[main]/Zabbix_agent::Install/Package[zabbix_agent]/ensure: change from 'absent' to 'present' failed: RPMs must specify a package source
Notice: /Stage[main]/Zabbix_agent::Config/File[zabbix_agent.conf]: Dependency Package[zabbix_agent] has failures: true
Warning: /Stage[main]/Zabbix_agent::Config/File[zabbix_agent.conf]: Skipping because of failed dependencies
Error: /Stage[main]/Zabbix_agent::Service/Service[zabbix_agent]: Provider init is not functional on this host. 

## Specifications
Puppet master: 5.5 running on centos 7

aio_agent_version => 5.5.17
apache_version => 2.4.6
augeas => {
  version => "1.12.0"
}
disks => {
  sda => {
    model => "Virtual disk",
    size => "16.00 GiB",
    size_bytes => 17179869184,
    vendor => "VMware"
  },
  sr0 => {
    model => "VMware IDE CDR10",
    size => "1.00 GiB",
    size_bytes => 1073741312,
    vendor => "NECVMWar"
  }
}
dmi => {
  bios => {
    release_date => "09/21/2015",
    vendor => "Phoenix Technologies LTD",
    version => "6.00"
  },
  board => {
    manufacturer => "Intel Corporation",
    product => "440BX Desktop Reference Platform",
    serial_number => "None"
  },
  chassis => {
    asset_tag => "No Asset Tag",
    type => "Other"
  },
  manufacturer => "VMware, Inc.",
  product => {
    name => "VMware Virtual Platform",
    serial_number => "VMware-42 2d cc bc cd dd d7 f1-68 a0 d7 88 9d b8 e1 a3",
    uuid => "422DCCBC-CDDD-D7F1-68A0-D7889DB8E1A3"
  }
}
facterversion => 3.11.10
filesystems => xfs
fips_enabled => false
hypervisors => {
  vmware => {
    version => "ESXi 6.0"
  }
}
identity => {
  gid => 0,
  group => "root",
  privileged => true,
  uid => 0,
  user => "root"
}
ip6tables_version => 1.4.21
iptables_version => 1.4.21
is_pe => false
is_virtual => true
kernel => Linux
kernelmajversion => 3.10
kernelrelease => 3.10.0-1062.4.1.el7.x86_64
kernelversion => 3.10.0
load_averages => {
  15m => 0.11,
  1m => 0.08,
  5m => 0.07
}
memory => {
  swap => {
    available => "930.86 MiB",
    available_bytes => 976080896,
    capacity => "43.24%",
    total => "1.60 GiB",
    total_bytes => 1719660544,
    used => "709.13 MiB",
    used_bytes => 743579648
  },
  system => {
    available => "372.84 MiB",
    available_bytes => 390946816,
    capacity => "79.72%",
    total => "1.80 GiB",
    total_bytes => 1927499776,
    used => "1.43 GiB",
    used_bytes => 1536552960
  }
}
mountpoints => {
  / => {
    available => "11.10 GiB",
    available_bytes => 11915395072,
    capacity => "17.09%",
    device => "/dev/mapper/centos-root",
    filesystem => "xfs",
    options => [
      "rw",
      "relatime",
      "attr2",
      "inode64",
      "noquota"
    ],
    size => "13.38 GiB",
    size_bytes => 14371782656,
    used => "2.29 GiB",
    used_bytes => 2456387584
  },
  /boot => {
    available => "785.79 MiB",
    available_bytes => 823955456,
    capacity => "22.51%",
    device => "/dev/sda1",
    filesystem => "xfs",
    options => [
      "rw",
      "relatime",
      "attr2",
      "inode64",
      "noquota"
    ],
    size => "1014.00 MiB",
    size_bytes => 1063256064,
    used => "228.21 MiB",
    used_bytes => 239300608
  },
  /dev => {
    available => "907.66 MiB",
    available_bytes => 951754752,
    capacity => "0%",
    device => "devtmpfs",
    filesystem => "devtmpfs",
    options => [
      "rw",
      "nosuid",
      "size=929448k",
      "nr_inodes=232362",
      "mode=755"
    ],
    size => "907.66 MiB",
    size_bytes => 951754752,
    used => "0 bytes",
    used_bytes => 0
  },
  /dev/hugepages => {
    available => "0 bytes",
    available_bytes => 0,
    capacity => "100%",
    device => "hugetlbfs",
    filesystem => "hugetlbfs",
    options => [
      "rw",
      "relatime"
    ],
    size => "0 bytes",
    size_bytes => 0,
    used => "0 bytes",
    used_bytes => 0
  },
  /dev/mqueue => {
    available => "0 bytes",
    available_bytes => 0,
    capacity => "100%",
    device => "mqueue",
    filesystem => "mqueue",
    options => [
      "rw",
      "relatime"
    ],
    size => "0 bytes",
    size_bytes => 0,
    used => "0 bytes",
    used_bytes => 0
  },
  /dev/pts => {
    available => "0 bytes",
    available_bytes => 0,
    capacity => "100%",
    device => "devpts",
    filesystem => "devpts",
    options => [
      "rw",
      "nosuid",
      "noexec",
      "relatime",
      "gid=5",
      "mode=620",
      "ptmxmode=000"
    ],
    size => "0 bytes",
    size_bytes => 0,
    used => "0 bytes",
    used_bytes => 0
  },
  /dev/shm => {
    available => "919.10 MiB",
    available_bytes => 963747840,
    capacity => "0%",
    device => "tmpfs",
    filesystem => "tmpfs",
    options => [
      "rw",
      "nosuid",
      "nodev"
    ],
    size => "919.10 MiB",
    size_bytes => 963747840,
    used => "0 bytes",
    used_bytes => 0
  },
  /run => {
    available => "910.16 MiB",
    available_bytes => 954376192,
    capacity => "0.97%",
    device => "tmpfs",
    filesystem => "tmpfs",
    options => [
      "rw",
      "nosuid",
      "nodev",
      "mode=755"
    ],
    size => "919.10 MiB",
    size_bytes => 963747840,
    used => "8.94 MiB",
    used_bytes => 9371648
  },
  /run/user/0 => {
    available => "183.82 MiB",
    available_bytes => 192753664,
    capacity => "0%",
    device => "tmpfs",
    filesystem => "tmpfs",
    options => [
      "rw",
      "nosuid",
      "nodev",
      "relatime",
      "size=188236k",
      "mode=700"
    ],
    size => "183.82 MiB",
    size_bytes => 192753664,
    used => "0 bytes",
    used_bytes => 0
  },
  /sys/fs/cgroup => {
    available => "919.10 MiB",
    available_bytes => 963747840,
    capacity => "0%",
    device => "tmpfs",
    filesystem => "tmpfs",
    options => [
      "ro",
      "nosuid",
      "nodev",
      "noexec",
      "mode=755"
    ],
    size => "919.10 MiB",
    size_bytes => 963747840,
    used => "0 bytes",
    used_bytes => 0
  }
}
mysql_server_id => 23259896
networking => {
  domain => "ulastirma.local",
  fqdn => "puppetmaster.ulastirma.local",
  hostname => "puppetmaster",
  interfaces => {
    ens160 => {
      bindings => [
        {
          address => "10.6.36.1",
          netmask => "255.255.255.0",
          network => "10.6.36.0"
        }
      ],
      bindings6 => [
        {
          address => "fe80::250:56ff:fead:6b38",
          netmask => "ffff:ffff:ffff:ffff::",
          network => "fe80::"
        }
      ],
      ip => "10.6.36.1",
      ip6 => "fe80::250:56ff:fead:6b38",
      mac => "00:50:56:ad:6b:38",
      mtu => 1500,
      netmask => "255.255.255.0",
      netmask6 => "ffff:ffff:ffff:ffff::",
      network => "10.6.36.0",
      network6 => "fe80::"
    },
    lo => {
      bindings => [
        {
          address => "127.0.0.1",
          netmask => "255.0.0.0",
          network => "127.0.0.0"
        }
      ],
      bindings6 => [
        {
          address => "::1",
          netmask => "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
          network => "::1"
        }
      ],
      ip => "127.0.0.1",
      ip6 => "::1",
      mtu => 65536,
      netmask => "255.0.0.0",
      netmask6 => "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
      network => "127.0.0.0",
      network6 => "::1"
    }
  },
  ip => "10.6.36.1",
  ip6 => "fe80::250:56ff:fead:6b38",
  mac => "00:50:56:ad:6b:38",
  mtu => 1500,
  netmask => "255.255.255.0",
  netmask6 => "ffff:ffff:ffff:ffff::",
  network => "10.6.36.0",
  network6 => "fe80::",
  primary => "ens160"
}
os => {
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.7.1908",
    major => "7",
    minor => "7"
  },
  selinux => {
    enabled => false
  }
}
package_provider => yum
partitions => {
  /dev/mapper/centos-root => {
    filesystem => "xfs",
    mount => "/",
    size => "13.39 GiB",
    size_bytes => 14382268416,
    uuid => "43d50dce-154b-42c8-bf50-8df881786b5a"
  },
  /dev/mapper/centos-swap => {
    filesystem => "swap",
    size => "1.60 GiB",
    size_bytes => 1719664640,
    uuid => "9d41d155-1f57-483e-932d-ba9e86735942"
  },
  /dev/sda1 => {
    filesystem => "xfs",
    mount => "/boot",
    size => "1.00 GiB",
    size_bytes => 1073741824,
    uuid => "52192c52-4f2a-40b1-b6bb-9703a5d3b683"
  },
  /dev/sda2 => {
    filesystem => "LVM2_member",
    size => "15.00 GiB",
    size_bytes => 16105078784,
    uuid => "Ugdzgw-vgFI-mPI2-kpse-QP4c-zT3S-1uNYX4"
  }
}
path => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/root/bin:/sbin
processors => {
  count => 2,
  isa => "x86_64",
  models => [
    "Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz",
    "Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz"
  ],
  physicalcount => 2
}
puppet_environmentpath => /etc/puppetlabs/code/environments
puppet_server => puppetmaster.ulastirma.local
puppet_vardir => /opt/puppetlabs/puppet/cache
puppetversion => 5.5.17
root_home => /root
ruby => {
  platform => "x86_64-linux",
  sitedir => "/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.4.0",
  version => "2.4.9"
}
selinux_semanage_is_python3 => false
service_provider => systemd
ssh => {
  ecdsa => {
}
system_uptime => {
  days => 1,
  hours => 30,
  seconds => 108715,
  uptime => "1 day"
}
systemd => true
systemd_internal_services => {
  systemd-bootchart.service => "disabled",
  systemd-nspawn@.service => "disabled",
  systemd-readahead-collect.service => "enabled",
  systemd-readahead-done.service => "indirect",
  systemd-readahead-drop.service => "enabled",
  systemd-readahead-replay.service => "enabled"
}
systemd_version => 219
timezone => +03
virtual => vmware

**Comment by alvagante** [comment]
Can't test it quickly but can you verify if it works by changing 'rpm' to 'yum' the value in this line: https://github.com/example42/puppet-zabbix_agent/blob/master/manifests/init.pp#L178 ?

**Comment by tuxmea** [comment]
@networkbiti can you please share the declaratoin of class zabbiz_agent?
If you use `include zabbix_agent` you can do two things:

1. Alessandros proposal
2. Declare zabbix_agent using class:
```
    class { 'zabbix_agent':
      package_provider => 'yum',
    }
```

**Comment by networkbiti** [comment]
thanks for replies.

i changed 'rpm' to 'yum' and dpgk to apt. 

 zabbix agent installed on ubuntu clients but it gives error: Error: /Stage[main]/Zabbix_agent::Service/Service[zabbix_agent]: Provider init is not functional on this host

and zabbix agent haven't intalled on redhat family clients. and it gives error:
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install zabbix-agent' returned 1: Error: Nothing to do

i run this comment standalone: /usr/bin/yum -d 0 -e 0 -y install zabbix-agent
outputs: Error: Nothing to do

Sory my english and less knowledge about puppet :(

**Comment by tuxmea** [comment]
@networkbiti 
The erorr on RedHat says you are missing the zabbix-agent yum repository and Redhat does not deliver a package by themselves. Yu need to add the official zabbix repo: https://repo.zabbix.com/zabbix/3.0/

Regarding the error with init : you can use to the following code:
```
    class { 'zabbix_agent':
      package_provider => $facts['package_provider'],
      service_provider => $facts['service_provider'],
    }
```
